name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write
  contents: write
  
jobs:
  PrintPayload:
    runs-on: ubuntu-latest
    steps:
      # use actions/script to access payload and print it
      - uses: actions/script@v6
        with:
          script: |
            console.log(JSON.stringify(context.payload))

