name: Check PR title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write
  contents: write
  
jobs:
  DetectCheckboxes:
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
    steps:
      - uses: airtonix/checkbox-action@v1.1.2
        id: detect
        with:
          action: 'detect'

  PrintCheckboxes:
    needs: DetectCheckboxes
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{needs.DetectCheckboxes.outputs.checked}}
